twodo:
  application:
    name: TwoDo
    version: 1.0.0
    schema: twodo_schema
    developer: Daniel Githiomi
    generateJwtSecretEnabled: false
    manualDBPopulationEnabled: false
    repository: https://github.com/danielgithiomi/twodo
    description: A personal bucket-list monorepo application for couples and friends to create, share, and track activities.

spring:
  application:
    name: TwoDo
    version: 1.0.0
  profiles:
    active: development
    default: production

server:
  port: 8080
