# Development Configuration
spring:
  # Import Secret Keys
  config:
    import: "optional:secret.properties"
  # Database Configuration (H2)
  datasource:
    url: jdbc:h2:mem:twodo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    username: dev
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      continue-on-error: false
  h2:
    console:
      path: /h2
      enabled: true

# Logging Configuration
logging:
  file:
    name: ./logs/development-logs.txt
