#!/usr/bin/env sh

commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

# Regex pattern:
# - Start with Feat, Fix, Ref, or Config
# - Space and section in parentheses e.g. (Root-Project)
# - Space and ticket id in quotes e.g. 'TNF-001':
# - Then a brief summary
pattern="^(Feat|Fix|Ref|Config) \([^)]+\) '[A-Z]+-[0-9]+':.+$"

if ! echo "$commit_msg" | grep -Eq "$pattern"; then
  echo "❌ Invalid commit message format."
  echo "Expected format: Config (Root-Project) 'TNF-001': Brief summary of changes"
  exit 1
fi
